import "./createOfficeTable.js";
import "./createRoleTable.js";
import "./createVisitorTable.js";
import "./createUserTable.js";
import "./createActivityLogTable.js";
import "./createVisitorLogTable.js";
import "./migrateLeftAt.js";
import "./migrateVisitLogVisitorImg.js";
import "./migrateBlueprintLifecycle.js";
